# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentInfo.name }}
  namespace: {{ .Values.deploymentInfo.namespace }}
  labels:
    app: {{ .Values.deploymentInfo.name }}
spec:
  replicas: {{ .Values.deploymentInfo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentInfo.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentInfo.name }}
    spec:
      containers:
        - name: {{ .Values.deploymentInfo.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deploymentInfo.port }}
              protocol: TCP