# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceInfo.name }}
  namespace: {{ .Values.deploymentInfo.namespace }}
spec:
  selector:
    app: {{ .Values.deploymentInfo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceInfo.targetPort }}
      targetPort: {{ .Values.deploymentInfo.port }}
  type: {{ .Values.serviceInfo.type }}